# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: article.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("article.proto", :syntax => :proto3) do
    add_message "Empty" do
    end
    add_message "GetRequest" do
      optional :id, :int32, 1
    end
    add_message "CreateReuqest" do
      optional :title, :string, 1
    end
    add_message "ArticleReply" do
      optional :id, :int32, 1
      optional :title, :string, 2
      optional :created_at, :string, 3
      optional :updated_at, :string, 4
    end
  end
end

Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Empty").msgclass
GetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetRequest").msgclass
CreateReuqest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CreateReuqest").msgclass
ArticleReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ArticleReply").msgclass
