# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: article.proto for package ''

require 'grpc'
require 'article_pb'

module Article
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Article'

    rpc :Get, ::GetRequest, ::ArticleReply
    rpc :List, ::Empty, stream(::ArticleReply)
    rpc :Create, ::CreateReuqest, ::ArticleReply
  end

  Stub = Service.rpc_stub_class
end
