# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: article.proto for package 'grpcapi.articles'

require 'grpc'
require 'article_pb'

module Grpcapi
  module Articles
    module Articles
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'grpcapi.articles.Articles'

        rpc :Get, ::Grpcapi::Articles::ID, ::Grpcapi::Articles::FullContent
        rpc :List, ::Grpcapi::Articles::Empty, ::Grpcapi::Articles::FullContent
        rpc :Create, ::Grpcapi::Articles::NewContent, ::Grpcapi::Articles::FullContent
        rpc :Update, ::Grpcapi::Articles::UpdatingContent, ::Grpcapi::Articles::FullContent
        rpc :Destroy, ::Grpcapi::Articles::ID, ::Grpcapi::Articles::FullContent
      end

      Stub = Service.rpc_stub_class
    end
  end
end
